load 'csspool/selectors/simple.rb'
load 'csspool/selectors/universal.rb'
load 'csspool/selectors/type.rb'
load 'csspool/selectors/additional.rb'
load 'csspool/selectors/id.rb'
load 'csspool/selectors/class.rb'
load 'csspool/selectors/pseudo_class.rb'
load 'csspool/selectors/attribute.rb'
