load 'csspool/terms/ident.rb'
load 'csspool/terms/string.rb'
load 'csspool/terms/number.rb'
load 'csspool/terms/function.rb'
load 'csspool/terms/uri.rb'
load 'csspool/terms/rgb.rb'
load 'csspool/terms/hash.rb'
